### ISSUE TITLE
[BUG] Websocket upgrades shouldn't be possible with POST requests.

### ISSUE THREAD

**Issue by ItsWendell** [mrbbot/miniflare#25]
Upgrading a request to WebSockets should only be possible with `GET` requests. I verified this in production and took me a while to figure out that this was the thing that was going wrong. The following code sample shouldn't work.

```ts
        const res = await durableObject.fetch(
          `http://fake-host/events/messageSend?clientId=${ctx.message.id}`,
          {
            method: 'POST',
            headers: {
              Upgrade: 'websocket'
            },
          },
        )
        console.log('has WebSocket', typeof res?.webSocket !== "undefined");
 ```

Took me a while to figure out why my code wasn't working in production but was working with Miniflare. this was the reason. Will be great to have this fixed in miniflare. 
 
I might be able to work on a PR this week. What are the preferences in terms of testing?

E.g. would a test called `test("fetch: only performs web socket upgrade on GET requests")` be ok?

In case I don't get round to it, I think it might be as simple as changing the following file: `src/modules/standards.ts`

before:
```ts
    // Handle web socket upgrades
    if (request.headers.get("upgrade") === "websocket") {
 ```

after:
```ts
    // Handle web socket upgrades, this should only for GET requests
    if (request.method === "GET" && request.headers.get("upgrade") === "websocket") {
```

**Comment by lukeed** [comment]
Yeah, [as per the spec](https://datatracker.ietf.org/doc/html/rfc6455#section-1.8) only GET requests can be upgraded
