### ISSUE TITLE
How to handle modules from npm?

### ISSUE THREAD

**Issue by savikko** [mrbbot/miniflare#46]
This might be stupid question but I'm buried deep under this problem. I have working repo, running at CF Worker.

I'm trying to use JWT package with
```js
import JWT from '@tsndr/cloudflare-worker-jwt';
```

But as I start `miniflare src/index.mjs -w -d` I get following error:

```bash
[mf:err] MiniflareError: Unable to resolve "src/index.mjs" dependency "@tsndr/cloudflare-worker-jwt": no matching module rules
```

I have dependency at `package.json`:
```json
    "dependencies": {
        "@cfworker/uuid": "^1.9.0",
        "@tsndr/cloudflare-worker-jwt": "^1.1.2"
    }
```

I am doing something wrong, but what?

**Comment by savikko** [comment]
Nevermind, I got this working.

**Comment by socketopp** [comment]
@savikko now how do you resolve it? I'm using itty-router and getting same error

**Comment by savikko** [comment]
I have to dig a little what I actually did. IIRC it required building it first once or so.
Will provide more details later, please ping me if it seems I forgot this :)
